### PR TITLE
configurable protocol

### PR DESCRIPTION
**Pull request by thinker0**
configurable protocol

### CODE REVIEW

**Comment by takezoe** [comment]
@thinker0 Thanks for your pull request! I'm thinking configuring complete url of the Zipkin server might be better as:
```
trace.zipkin.server-url = "https://localhost:9411"
```
How do you think about this idea?

**Comment by adriancole** [comment]
I think many libraries use baseUrl for this

**Comment by adriancole** [comment]
another way is to say zipkin.endpoint as this allows you to configure the path which can change when people proxy it https://github.com/openzipkin/zipkin-reporter-java/blob/master/okhttp3/src/main/java/zipkin/reporter/okhttp3/OkHttpSender.java#L73

**Comment by takezoe** [comment]
@adriancole Thanks, I chose`base-url` in #20.

**Comment by takezoe** [comment]
@thinker0 Since this pull request is covered by #20 I close. If you have any opinion, please add comment there.

**Comment by thinker0** [comment]
LGTM!

**Pull request closed without merging**
