### PR TITLE
Support for Play 2.7.0

### PR DESCRIPTION
**Pull request by shimamoto**

### CODE REVIEW

**Comment by shimamoto** [comment]
@takezoe Please take a review when you have time.

**Comment by adriancole** [comment]
maybe I can help with this.

**Comment by takezoe** [comment]
I got an error below with the combination of a newer version of play-zipkin-tracing and an older version of play-zipkin-tracing in the older version side:
```
[warn] z.r.AsyncReporter$BoundedAsyncReporter - Dropped 1 spans due to IllegalStateException(response failed: Response{protocol=http/1.1, code=400, message=Bad Request, url=http://localhost:9411/api/v1/spans})
java.lang.IllegalStateException: response failed: Response{protocol=http/1.1, code=400, message=Bad Request, url=http://localhost:9411/api/v1/spans}
	at zipkin.reporter.okhttp3.OkHttpSender$CallbackAdapter.onResponse(OkHttpSender.java:262) [zipkin-sender-okhttp3-0.10.0.jar:na]
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:141) [okhttp-3.8.0.jar:na]
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) [okhttp-3.8.0.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_191]
[warn] z.r.AsyncReporter$BoundedAsyncReporter - Dropped 2 spans due to IllegalStateException(response failed: Response{protocol=http/1.1, code=400, message=Bad Request, url=http://localhost:9411/api/v1/spans})
java.lang.IllegalStateException: response failed: Response{protocol=http/1.1, code=400, message=Bad Request, url=http://localhost:9411/api/v1/spans}
	at zipkin.reporter.okhttp3.OkHttpSender$CallbackAdapter.onResponse(OkHttpSender.java:262) [zipkin-sender-okhttp3-0.10.0.jar:na]
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:141) [okhttp-3.8.0.jar:na]
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) [okhttp-3.8.0.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_191]
```
We have two applications to test nested API call tracing. The first one is Play 2.7 application with the latest version of play-zipkin-tracing. It calls the second one that is Play 2.4 application with the older version of play-zipkin-tracing which supports only zipkin-v1. Zipkin server I tested is `zipkin-server-2.12.3-exec.jar`.

@adriancole Is this an expected behavior?

**Comment by adriancole** [comment]
problem is that we have text in the http body that would explain why it dropped. I think we need to update the zipkin-reporter library to include that in the error message. Usually it is when you send v2 format to the v1 endpoint. cc @shakuzen

**Comment by adriancole** [comment]
@takezoe I have narrowed this down to the first byte that is supposed to be 12 (thrift list), but gzipping back as 11.

**Comment by takezoe** [comment]
@adriancole Thanks for quick fix! In my understanding, we will able to handle requests from the v1 okhttp reporter if we use the next version of zipkin-server. Right? 

Anyway, I think we can merge this pull request. @shimamoto

**Comment by adriancole** [comment]
I agree. very soon 2.12.4 will workaround the v1 okhttp reporter bug,
something we never noticed before. There's no change needed here.

**Comment by shimamoto** [comment]
@takezoe @adriancole many thanks!

**Pull request merged**
